version: '3.9'

services:
    shore-app:
        container_name: shore-app
        image: shore-app
        stdin_open: true
        tty: true
        build: .
        stdin_open: true
        environment:
            - FLASK_MAIL=enabled
            - DEBUG=False
        command: bash runner.sh
        tty: true
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            shore-app-db:
              condition: service_healthy
    shore-app-db:
        container_name: shore-app-db
        image: mysql
        ports:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=zxc90zxc
            - MYSQL_ROOT_HOST=%
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            timeout: 20s
            retries: 10
            start_period: 20s
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
    shore-app-worker:
        container_name: shore-app-worker
        build: .
        image: shore-app-worker
        command: celery -A shore_app.tasks.celery worker --concurrency=20 -Q create_product_from_ebay,check_subscription_and_sent_alert --loglevel=INFO
        depends_on:
          - shore-app-db
          - shore-app-beat
          - redis
        restart: 'no'
        volumes: 
          - .:/code
        depends_on:
          shore-app-db:
            condition: service_healthy
    shore-app-beat:
        container_name: shore-app-beat
        build: .
        image: shore-app-beat
        command: celery -A shore_app.tasks.celery beat --loglevel=INFO
        depends_on: 
          - redis
        restart: 'no'
        volumes: 
          - .:/code
        depends_on:
          redis:
            condition: service_healthy
    redis:
        container_name: shore-redis
        image: redis:6-alpine
        healthcheck:
          test: redis-cli PING
