version: '2.1'

services:
    shore-app:
        container_name: shore-app
        image: shore-app
        stdin_open: true
        tty: true
        build: .
        stdin_open: true
        environment:
            - FLASK_MAIL=disabled
            - DEBUG=False
        tty: true
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - shore-app-db
            - redis
    worker:
        container_name: shore-app-worker
        build: .
        image: shore-app-worker
        command: celery -A shore_app.tasks.celery worker --concurrency=20 --loglevel=INFO
        depends_on:
          - beat
          - redis
        restart: 'no'
        volumes: 
          - .:/code
    beat:
        build: .
        image: shore-app-beat
        command: celery -A shore_app.tasks.celery beat --loglevel=INFO
        depends_on: 
          - redis
        restart: 'no'
        volumes: 
          - .:/code
    shore-app-db:
        container_name: shore-app-db
        image: mysql
        # command: --init-file /docker-entrypoint-initdb.d/1-init.sql
        ports:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=zxc90zxc
            - MYSQL_ROOT_HOST=%
        healthcheck:
            test: mysql -uroot -pzxc90zxc -e 'select 1'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d

    redis:
        container_name: shore-redis
        image: redis:6-alpine
