version: '2.1'

services:
    shore-app:
        container_name: shore-app
        stdin_open: true
        tty: true
        build: .
        # command: celery worker --app=shore_app.tasks.celery --loglevel=info
        stdin_open: true
        tty: true
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - shore-app-db
            - redis
    shore-app-db:
        container_name: shore-app-db
        image: mysql
        # command: --init-file /docker-entrypoint-initdb.d/1-init.sql
        ports:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=zxc90zxc
            - MYSQL_ROOT_HOST=%
        healthcheck:
            test: mysql -uroot -pzxc90zxc -e 'select 1'
        volumes:
            - .:/docker-entrypoint-initdb.d

    redis:
        container_name: shore-redis
        image: redis:6-alpine
